version: '2'
services:
back:
    build: ./back
    ports:
      - '4242:4242'
    depends_on:
      - api
front:
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'